Feat/6
f-lab-edu/Share-The-Journey pull request #10
Opened 2024-06-28 16:37 UTC by ohgus

## 로그인 페이지 레이아웃 구현

이슈번호: #6 

- 이메일 입력란
- 비밀번호 입력란
- 회원가입 버튼
- 로그인 버튼

<img width="536" alt="image" src="https://github.com/f-lab-edu/Share-The-Journey/assets/123801385/f5e07f58-0d9a-49aa-abbc-f5261e91d7bc">

2024-06-29 12:36 UTC, joonhok-fittube requested changes

2024-06-29 12:36 UTC, joonhok-fittube commented on src/app/login/page.tsx
> +          <button
여기도 <Link> 컴포넌트가 쓰여야 될 것 같네요.

2024-06-29 17:00 UTC, ohgus commented on src/app/login/page.tsx
> +          <button
@joonhok-fittube 회원가입 문구랑 회원가입 버튼을 하나의 컴포넌트로 묶는게 좋다는 말씀이신가요?

2024-06-30 03:23 UTC, joonhok-fittube commented on src/app/login/page.tsx
> +          <button
@ohgus 
아이고, 제 코멘트가 이상하게 작성됐네요. "여기도 <Link /> 컴포넌트를 쓰셔야 될 것 같네요."라고 적으려고 했는데 이상하게 <Link /> 부분이 빠졌습니다. 

"Sign Up" 버튼을 누르면 회원 가입 페이지로 이동해야 되는 부분을 말씀드렸습니다.

2024-06-30 10:18 UTC, ohgus commented on src/app/login/page.tsx
> +          <button
@joonhok-fittube 혹시 `Link` 태그 말씀하시는 걸까요?? 그 부분은 회원가입 페이지 pr에서 수정했습니다!

2024-07-01 02:24 UTC, joonhok-fittube commented on src/app/login/page.tsx
> +          <button
아, 이게 Link 태그를 꺽쇠랑 같이 적으면 자동으로 제외가 되네요? 네, Link 태그를 말씀드린게 맞습니다.

네, 그럼 머지하셔도 될 것 같습니다!

2024-07-01 08:14 UTC, merged