[#8] 여행지 등록 페이지 레이아웃 구현
f-lab-edu/Share-The-Journey pull request #12
Opened 2024-06-28 16:46 UTC by ohgus

## 여행지 등록 페이지 레이아웃 구현

이슈번호: #8 

로그인, 회원가입, 여행지 등록 모두 비슷한 레이아웃을 기반으로 작업했습니다.

여행지 등록 페이지의 경우 작업이 어느정도 마무리되고 더 좋은 디자인을 찾게되면 디자인 변경을 고려할 예정입니다.

- 여행지 이름
- 여행지 위치
- 가격
- 편의시설
- 한줄평
- 별점
- 사진
- 등록버튼

<img width="786" alt="image" src="https://github.com/f-lab-edu/Share-The-Journey/assets/123801385/7d61b3ef-15d9-443d-8014-ceda8b865804">

2024-06-29 12:33 UTC, joonhok-fittube requested changes
수고하셨습니다. 그런데 UI를 바꿔서 조금만 더 사용하기 편리하게 만들어 봅시다.

1. 편의 시설은 Chip list로 구현해서 미리 정의해 놓은 편의 시설 목록 중에 사용자가 선택하도록 하면 좋을 듯합니다. [JoyUI](https://mui.com/joy-ui/react-chip/#with-a-checkbox)나 [nextui](https://nextui.org/docs/components/chip#list-of-chips) 중 하나를 설치해서 구현해보세요.
2. 파일 업로드 버튼도 테일윈드 만으로도 조금 더 예쁘게 꾸밀 수 있습니다. 이 링크를 참조해주세요. https://tailwindcss.com/docs/hover-focus-and-other-states#file-input-buttons
3.

2024-06-30 03:27 UTC, joonhok-fittube commented
@ohgus 
그리고 한 가지만 더 개선하자면, 가격을 입력하는 부분도 통화(원화인지 달러인지) 부분은 미리 고정해놓거나 정해진 옵션들 중에 선택할 수 있게 해주고, 사용자는 숫자 값만 입려하도록 구현해 놓으면 더 편리할 것 같습니다. 다음 링크들을 참조해주세요.
https://nextui.org/docs/components/input#start--end-content
https://mui.com/joy-ui/react-input/#decorators

2024-06-30 16:09 UTC, ohgus commented
@joonhok-fittube 
<img width="707" alt="image" src="https://github.com/f-lab-edu/Share-The-Journey/assets/123801385/107711b3-6bc7-4ca1-9a0e-19ae0b58b9aa">

`file input`을 제외하고는 모두 `nextui`를 사용해서 리팩토링했습니다!
그리고 편의시설의 경우 체크박스를 적용했는데 라디오랑 체크박스 중에서 어떤게 더 좋은 선택지인지 고민이됩니다!

`input`을 감싸는 부모에 `flex flex-wrap`을 사용하지 않으면 `input`이 서로 묘하게 겹치는 느낌이 들어서 공식문서를 따라서 적용했는데 이렇게 하는것이 맞는지 궁굼합니다.

2024-07-01 02:29 UTC, joonhok-fittube requested changes
그리고 편의 시설에는 체크 박스를 사용하셔야 됩니다. 라디오 버튼은 여러 옵션 중에 하나만 선택할 수 있을 때 사용하시는 UI인데, 편의 시설은 여러 개를 선택할 수 있어야 하기 때문입니다.

input 부분은 잘 처리하신 것 같습니다.

2024-07-01 02:29 UTC, joonhok-fittube commented on package.json
> +    "@nextui-org/checkbox": "^2.1.2",
`@nextui-org/react`를 설치했으면 개별 컴포넌트를 따로 또 설치할 필요는 없습니다.

2024-07-01 08:17 UTC, ohgus commented on package.json
> +    "@nextui-org/checkbox": "^2.1.2",
@joonhok-fittube 제거했습니다!

2024-07-06 08:27 UTC, merged