[#15] 여행지 데이터 불러오는 api 생성
f-lab-edu/Share-The-Journey pull request #16
Opened 2024-07-01 12:18 UTC by ohgus

## hellow, world api를 여행지 데이터 불러오는 api로 수정

관련이슈: #15 

- api 변환 (hellow, world -> 여행지 data)
- 홈페이지에 적용

2024-07-02 01:56 UTC, joonhok-fittube requested changes

2024-07-02 01:56 UTC, joonhok-fittube commented on src/app/api/places/route.ts
> +const places = [
이 변수는 Place type을 만들어서 Place[] 로 타이핑해주세요.

2024-07-02 12:34 UTC, ohgus commented on src/app/api/places/route.ts
> +const places = [
@joonhok-fittube 기존에 만들어둔 `PlaceDetailProps` 타입을 사용해도 될까요?

2024-07-04 00:34 UTC, joonhok-fittube commented on src/app/api/places/route.ts
> +const places = [
@ohgus 아, 네 제가 답변이 좀 늦었네요. 물론 기존 타입을 이용하셔도 괜찮습니다.

2024-07-04 00:35 UTC, joonhok-fittube approved these changes

2024-07-04 04:26 UTC, merged