[#18] 파이어베이스 authentication 연동하기
f-lab-edu/Share-The-Journey pull request #19
Opened 2024-07-06 08:20 UTC by ohgus

## Authentication 구현하기

관련이슈: #18 

- 로그인
- 회원가입
  - 닉네임 설정
- 로그아웃
- 로그인, 회원가입, 로그아웃하면 홈페이지로 리다이렉트

2024-07-08 02:05 UTC, joonhok-fittube requested changes

2024-07-08 02:05 UTC, joonhok-fittube commented on src/components/Header.tsx
> +    onAuthStateChanged(auth, (user) => {
auth state 같은건 이 Header 컴포넌트에서 뿐만 아니라 다른 많은 컴포넌트에서 사용될 수 있기 때문에 보통 Context로 구현합니다.

https://kentcdodds.com/blog/authentication-in-react-applications

이 링크를 참조해서 변경해주세요

2024-07-08 09:44 UTC, ohgus commented on src/components/Header.tsx
> +    onAuthStateChanged(auth, (user) => {
@joonhok-fittube 
컨텍스트 적용했습니다!

2024-07-09 01:11 UTC, joonhok-fittube requested changes

2024-07-09 01:11 UTC, joonhok-fittube commented on src/app/AuthContext.ts
> +  setUser: (user: User | null) => {},
AuthContext에서 `setUser`api 를 제공해줄 필요는 없습니다.

2024-07-09 01:11 UTC, joonhok-fittube commented on src/app/AuthProvider.tsx
> +    const auth = getAuth();
사소한 것이지만 `const auth = getAuth();`는 `useEffect` 훅 바깥에, 아예 `AuthProvider` 바깥에 두셔도 됩니다.

2024-07-09 01:11 UTC, joonhok-fittube commented on src/app/login/page.tsx
> +        setUser(res.user);
AuthContext에서 처리되기 때문에 여기서는 `setUser(res.user);`를 할 필요가 없습니다. `router.push('/');`가 되면 메인 페이지에서 `const { user } = useContext(AuthContext);` 를 호출할 때 `user` 객체가 있을 것입니다.

2024-07-09 08:12 UTC, ohgus commented on src/app/login/page.tsx
> +        setUser(res.user);
@joonhok-fittube 
`setUser`를 하지 않아도 유저의 정보가 자동으로 저장된다는 말씀이신가요?

2024-07-09 08:14 UTC, joonhok-fittube commented on src/app/login/page.tsx
> +        setUser(res.user);
@ohgus 네, 맞습니다.

2024-07-09 08:15 UTC, ohgus commented on src/app/login/page.tsx
> +        setUser(res.user);
아니면 `setUser`를 다른 곳에서 처리해야 한다는 말씀이신가요?

2024-07-09 08:21 UTC, joonhok-fittube commented on src/app/login/page.tsx
> +        setUser(res.user);
@ohgus 아니요, 다른 곳에서도 처리할 필요 없습니다. 우리는 `onAuthStateChanged` 콜백에서 넘겨주는 유저 정보를 AuthContext의 상태에서 setUser로 저장하고 그렇게 저장된 상태를 value로 다른 컴포넌트들에 제공해주면 충분합니다.

2024-07-09 08:39 UTC, ohgus commented on src/app/login/page.tsx
> +        setUser(res.user);
@joonhok-fittube 이해했습니다!

2024-07-09 08:48 UTC, ohgus commented
@joonhok-fittube 수정했습니다!

2024-07-09 09:02 UTC, joonhok-fittube commented on src/app/AuthProvider.tsx
> +  }, [auth]);
이렇게 하셔도 상관은 없는데, `const auth = getAuth();`를 아예 `AuthProvider` 바깥으로 빼버리면 `auth`를 의존성 배열에서 뺄 수 있습니다.

2024-07-09 09:03 UTC, joonhok-fittube commented on src/app/AuthProvider.tsx
> +  const value = useMemo(() => ({ user }), [user]);
여기서 useMemo를 쓰는건 중복입니다. 쓸 필요가 전혀 없습니다. 이 라인은 삭제하시고 그냥 24번째 라인에서 `value={{user}}` 하시면 됩니다. 그리고 왜 그렇게 해도 되는지 `useMemo` 레퍼런스 문서를 보시고 이해해보세요. 

https://react.dev/reference/react/useMemo

2024-07-09 10:10 UTC, ohgus commented on src/app/AuthProvider.tsx
> +  }, [auth]);
`getAuth`를 외부로 추출하면 파이어베이스가 초기화되지 않았다는 오류가 발생해서 안으로 다시 넣었는데 `AuthProvider`의 위치가 잘못된걸까요?

2024-07-09 10:15 UTC, ohgus commented on src/app/AuthProvider.tsx
> +  }, [auth]);
제가 `auth`를 `auth.ts`에서  따로 호출했는데 이걸 가져와서 사용하는 것을 깜빡했습니다!

2024-07-09 10:16 UTC, ohgus commented on src/app/AuthProvider.tsx
> +  const value = useMemo(() => ({ user }), [user]);
useMemo는 메모제이션을 위한 api인데 이미 파이어베이스에서 데이터를 저장해 연동하고 있기 때문인걸로 이해했는데 맞을까요?

2024-07-14 06:15 UTC, merged