Feat/1 홈페이지 레이아웃 구현 (데스크톱 버전)
f-lab-edu/Share-The-Journey pull request #2
Opened 2024-06-13 07:25 UTC by ohgus

# 홈페이지 레이아웃 구현 (데스크톱 버전)

연관된 이슈: #1 

- 헤더 컴포넌트 구현
- 검색바 컴포넌트 구현
- 홈페이지 타이틀 영역 컴포넌트 구현
- 카드 컴포넌트 구현
- 여행지, 리뷰 `mock-data` 준비

## 리뷰 요청사항
- 카드 컴포넌트를 구현했는데 이미지의 높이가 원본 사이즈에 따라 자꾸 자동으로 세팅되는 문제가 있습니다. 
  - 이 문제는 별도의 이슈를 생성해 해결하겠습니다.
- 아직 컴포넌트를 별도의 파일로 분리하지 못했습니다. 다른 페이지들 작업하면서 별도의 파일로 추출하겠습니다.

2024-06-17 04:58 UTC, joonhok-fittube requested changes
`BigCard`, `SearchBar`, `Header`는 /src/components 디렉토리를 만들어서 여기에 별도의 파일로(BigCard.tsx, SearchBar.tsx 등) 이동시켜 주세요. 그렇게 하시는게 관리하는데 더 편리합니다.

2024-06-17 04:58 UTC, joonhok-fittube commented on src/app/globals.css
> +  margin: 0 auto;
1. 테일윈드를 쓸 때는 기본적으로 테일윈드 클래스를 이용해서 스타일링 해주세요. `layout.tsx` 파일 <body> 태그에 테일윈드 클래스로 스타일링 하시면 됩니다.
2.  `width`를 하드코딩하는건 별로 좋지 않은 스타일링입니다. 테일윈드의 `container` 클래스를 찾아보시고 그 클래스 사용을 검토해주세요. 참고로 `container` 클래스에서 마진도 같이 세팅됩니다.

2024-06-17 04:58 UTC, joonhok-fittube commented on src/app/page.tsx
> +  const data = JSON.parse(jsonData);
`places.json` 파일을 `/src/app` 위치로 이동시키면 `fs`나 `path` 같은 모듈 쓰지 않고도 바로 임포트해서 쓰실 수 있을 겁니다.

2024-06-17 10:58 UTC, ohgus commented on src/app/globals.css
> +  margin: 0 auto;
수정하겠습니다~

2024-06-17 10:58 UTC, ohgus commented on src/app/page.tsx
> +  const data = JSON.parse(jsonData);
수정하겠습니다~

2024-06-18 01:04 UTC, joonhok-fittube approved these changes
LGTM

2024-06-18 07:35 UTC, merged