[#23] 여행지 상세 페이지 댓글 기능 구현
f-lab-edu/Share-The-Journey pull request #24
Opened 2024-07-15 09:23 UTC by ohgus

## 댓글 기능 구현

관련 이슈: #23 

- 여행지 상세 페이지에서 댓글을 작성할 수 있다.
- 로그인한 유저라면 작성자에 유저 이름을 아니라면 비회원이 작성한 댓글임을 명시한다.
- 댓글은 별도의 컬렉션으로 관리되며 어느 여행지의 리뷰인지 여행지의 id를 같이 포함하여 상세 페이지에 들어갔을 때 해당 여행지의 리뷰만 조회할 수 있다.

### 리뷰 요청
- #22 에서 분기된 브랜치 입니다.
- 별점 기능은 추후에 추가 구현하기 위해 우선 주석으로 처리했습니다.
- 리뷰에 관련된 코드의 양이 많아져 컴포넌트를 따로 분리했습니다.

2024-07-18 10:00 UTC, joonhok-fittube requested changes

2024-07-18 10:00 UTC, joonhok-fittube commented on src/components/ReviewArea.tsx
> +      writer: user?.displayName ?? '비회원',
이 필드에는 displayName을 저장할 것이 아니라 user.uid를 저장해야 나중에 사용자 별로 작성한 리뷰를 편리하게 읽어올 수 있습니다.

2024-07-18 10:00 UTC, joonhok-fittube commented on src/components/ReviewArea.tsx
> +      date: new Date().toISOString().split('T')[0],
보통 이런 값들은 unix timestamp를 사용합니다.

2024-07-18 10:00 UTC, joonhok-fittube commented on src/components/ReviewArea.tsx
> +      id: '',
이 값도 필요 없으니까 삭제하시면 됩니다.

2024-07-18 11:16 UTC, ohgus commented on src/components/ReviewArea.tsx
> +      writer: user?.displayName ?? '비회원',
@joonhok-fittube 
이 부분은 유저가 댓글을 남겼을 때 댓글에 보여지는 이름인데 uid를 공개하는 것이 좋을까요?
uid를 저장하고 displayName은 보여지게하고 uid는 조회에서만 사용되는 것이 좋을까요?

2024-07-18 11:30 UTC, ohgus commented on src/components/ReviewArea.tsx
> +      date: new Date().toISOString().split('T')[0],
수정했습니다!

2024-07-18 11:45 UTC, ohgus commented on src/components/ReviewArea.tsx
> +      id: '',
@joonhok-fittube 해당 값은 key에 사용되는데 필요하지 않을까요?

2024-07-28 07:23 UTC, ohgus commented on src/components/ReviewArea.tsx
@joonhok-fittube 에러가 발생했을 때 이전 페이지로 돌아가는 방식으로 처리했는데 더 좋은 방법이 있을까요?

2024-07-29 06:01 UTC, joonhok-fittube commented on src/components/ReviewArea.tsx
@ohgus 
지금 코드는 에러 메시지를 콘솔에 프린트하도록 되어 있는데, 일반 사용자는 콘솔 메시지를 보지는 않습니다. 그래서 일반 사용자 입장에서는 오류가 발생하는 경우 무슨 오류가 생겼는지도 모르고 이전 화면으로 돌아가게 될 거에요.

그것보다는 차라리 그냥 `ReviewCard`의 내용을 보여주는 영역에 오류가 발생했다고 안내 메시지를 보여주는 편이 낫겠습니다. 즉, 리뷰 데이터 대신에 오류 메시지를 보여주세요.

2024-07-29 09:02 UTC, ohgus commented on src/components/ReviewArea.tsx
리뷰 영역에 아예 다른 컨텐츠를 렌더링한다고 이해하면 될까요?

2024-07-30 04:00 UTC, joonhok-fittube commented on src/components/ReviewArea.tsx
@ohgus 네, 맞습니다!

2024-07-30 15:02 UTC, ohgus commented on src/components/ReviewArea.tsx
@joonhok-fittube 수정했는데 말씀하신게 이런 느낌이 맞는지 헷갈리네요 ㅜ

2024-07-31 09:33 UTC, joonhok-fittube approved these changes

2024-07-31 09:51 UTC, merged