[#37] 회원가입 폼 유효성 검사 추가
f-lab-edu/Share-The-Journey pull request #38
Opened 2024-08-05 05:43 UTC by ohgus

관련 이슈: #37 

## 작업 목록
- Next Ui 컴포넌트 적용 (Input, Button)
- email 검사 추가 (중복, 올바른 형식)
- 비밀번호 검사 추가 (6자 미만)

이메일 형식은 validate 검사로 로직을 따로 추가했고 나머지는 firebase에서 리턴해주는 에러 메시지를 읽고 상황에 맞게 에러 메시지를 띄워주게 설정했습니다.

2024-08-06 12:00 UTC, joonhok-fittube requested changes

2024-08-06 12:00 UTC, joonhok-fittube commented on src/app/signUp/page.tsx
> +  const [error, setError] = useState('');
이렇게 올 수 있는 값들이 한정된 경우에는 union literal type으로 타이핑 해주시는게 좋습니다.

`const [error, setError] = useState<'email' | 'invalid' | 'password' | null>(null);`

2024-08-06 12:43 UTC, ohgus commented on src/app/signUp/page.tsx
> +              errorMessage="비밀번호는 6자 이상이어야 합니다."
파이어베이스 [공식문서](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/auth/FirebaseAuthWeakPasswordException)에 6자미만의 비밀번호를 설정할 때 리턴되는 값이라고 확인했습니다!

2024-08-06 12:46 UTC, ohgus commented on src/app/signUp/page.tsx
> +  const [error, setError] = useState('');
수정했습니다!

2024-08-06 12:46 UTC, ohgus commented on src/utils/validate.ts
> +  if (emailRegex.test(email)) {
테스트 코드를 해당 pr에서 같이 작성하는게 좋을까요?

2024-08-07 04:56 UTC, ohgus commented on src/utils/validate.ts
> +  if (emailRegex.test(email)) {
@joonhok-fittube 테스트 코드 추가했습니다!

2024-08-07 11:30 UTC, joonhok-fittube commented on src/utils/validate.ts
> +  if (emailRegex.test(email)) {
네, 확인하겠습니다!

2024-08-07 11:30 UTC, joonhok-fittube commented on src/app/signUp/page.tsx
> +              errorMessage="비밀번호는 6자 이상이어야 합니다."
아하, 잘하셨습니다!

2024-08-07 11:33 UTC, joonhok-fittube approved these changes
수고하셨습니다!

2024-08-07 11:41 UTC, merged