여행지 상세 페이지 레이아웃 구현
f-lab-edu/Share-The-Journey pull request #4
Opened 2024-06-17 15:40 UTC by ohgus

## 여행제 상세 페이지 레이아웃

관련 이슈: #3 

### 사진 영역

- 현재는 그냥 이미지를 보여주나 추후에 케러셀 적용 예정

### 장소 정보 영역
- 이름, 등록자, 위치, 가격, 주변 시설, 한줄평 등의 정보를 보여준다.
 
![image](https://github.com/f-lab-edu/Share-The-Journey/assets/123801385/178a3031-f8f7-4490-b23d-858e31c01edd)

### 리뷰 영역
- 작성자, 별점, 리뷰, 작성일
- 리뷰 작성 폼

![image](https://github.com/f-lab-edu/Share-The-Journey/assets/123801385/de445227-5f98-4db8-93a5-83c0284bf1bd)

### 참고사항
- `feat/1`브랜치에서 분기하여 작업했습니다. 41312d7d19e0e6af5d501546070a7581a59f285b 커밋부터 봐주시면 될거 같습니다!
- 디테일 페이지 내부 컴포넌트들은 해당 페이지에서만 쓰일것 같아서 따로 분리를 안했는데 분리를 하는 편이 좋을까요?
- `BigCard` 컴포넌트에 사용된 `type`과 중복되는 부분이 있는거 같은데 `type`을 따로 추출해서 공통적으로 사용하는 편이 좋을까요?
- 세부적인 디자인은 모든 구현이 끝나고 수정할 예정입니다! 현재는 기본적인 디자인과 틀을 우선으로 구현하였습니다!

2024-06-18 01:40 UTC, joonhok-fittube requested changes
추가로 질문 주신 사항들에 대해 답변드립니다.

- feat/1브랜치에서 분기하여 작업했습니다. https://github.com/f-lab-edu/Share-The-Journey/commit/41312d7d19e0e6af5d501546070a7581a59f285b 커밋부터 봐주시면 될거 같습니다!
    - 네 그래서 이 PR을 `feat/3` 브랜치를 `feat/1` 브랜치에 머지하는 것으로 변경하였습니다. 이렇게 하면 두 브랜치가 정확히 어느 커밋부터 분기되는지를 정확히 볼 수 있습니다. 단, 머지하실 때는 이 PR을 먼저 머지하시고 그 다음 `feat/1` 브랜치를 `main`에 머지하시거나, `feat/1`이 먼저 `main`에 머지가 됐으면 이 PR을 `main`으로 머지되도록 업데이트해주셔야 합니다. 
- 디테일 페이지 내부 컴포넌트들은 해당 페이지에서만 쓰일것 같아서 따로 분리를 안했는데 분리를 하는 편이 좋을까요?
    - 아직까지는 분리 안하셔도 될 것 같습니다.
- BigCard 컴포넌트에 사용된 type과 중복되는 부분이 있는거 같은데 type을 따로 추출해서 공통적으로 사용하는 편이 좋을까요?
    - 네, 그게 낫겠습니다.
- 세부적인 디자인은 모든 구현이 끝나고 수정할 예정입니다! 현재는 기본적인 디자인과 틀을 우선으로 구현하였습니다!
    - 잘하셨습니다!

2024-06-18 01:40 UTC, joonhok-fittube commented on src/components/BigCard.tsx
> +const BigCard = ({ imgUrl, name, score, location, price, id }: CardProps) => {
컴포넌트 이름이 BigCard인데 컴포넌트 이름만 봐서는 이 컴포넌트가 어떤 컴포넌트인지 알기가 어렵습니다. 이름을 좀 더 컴포넌트의 내용을 잘 표현할 수 있도록 업데이트해주세요.

2024-06-18 01:40 UTC, joonhok-fittube commented on src/app/detail/[id]/page.tsx
> +type PlaceProps = {
프롭 속성들 중에 값이 없을 수 있는 속성들에 대해서는 옵셔널 속성으로 선언하는 게 좋을 것 같습니다.

2024-06-18 01:40 UTC, joonhok-fittube commented on src/app/detail/[id]/page.tsx
> +        가격 정보: {price > 0 ? `${price.toLocaleString()}$` : 'free'}
이게 달러로 표시되는게 맞나요? 그리고 이렇게 화폐를 포매팅하는 부분은 currency.js 같은 라이브러리르 사용하시는게 편리합니다.

2024-06-18 01:40 UTC, joonhok-fittube commented on src/app/detail/[id]/page.tsx
> +                작성일: {review.date.replace(/-/g, '.')}
이 부분은 date-fns 같은 라이브러리를 이용해서 수정해주세요.

2024-06-18 07:39 UTC, ohgus commented on src/app/detail/[id]/page.tsx
> +        가격 정보: {price > 0 ? `${price.toLocaleString()}$` : 'free'}
넵 화폐 단위는 달러로 표시한게 맞습니다!
`currency.js` 찾아보고 적용하겠습니다!

2024-06-18 08:32 UTC, ohgus commented on src/app/detail/[id]/page.tsx
> +        src={place!.imgUrl}
이 부분은 404페이지를 만들면서 수정하겠습니다!

2024-06-18 09:23 UTC, ohgus commented on src/app/detail/[id]/page.tsx
> +      <p className="mb-3">주변시설: 주차장 있음, 화장실 있음</p>
수정했습니다!

2024-06-18 09:45 UTC, ohgus commented on src/app/detail/[id]/page.tsx
> +                작성일: {review.date.replace(/-/g, '.')}
수정했습니다!

2024-06-18 09:53 UTC, ohgus commented on src/app/detail/[id]/page.tsx
> +        가격 정보: {price > 0 ? `${price.toLocaleString()}$` : 'free'}
@joonhok-fittube 해당 라이브러리를 권장하시는 이유는 부동소수점 이슈 때문일까요??

2024-06-18 10:35 UTC, ohgus commented on src/components/BigCard.tsx
> +const BigCard = ({ imgUrl, name, score, location, price, id }: CardProps) => {
홈에서 사용되는 장소 카드라는 의미로 `HomePlaceCard`로 수정했습니다!

2024-06-18 10:57 UTC, ohgus commented on src/app/detail/[id]/page.tsx
> +        가격 정보: {price > 0 ? `${price.toLocaleString()}$` : 'free'}
수정했습니다!

2024-06-19 04:04 UTC, joonhok-fittube commented on src/app/detail/[id]/page.tsx
> +        가격 정보: {price > 0 ? `${price.toLocaleString()}$` : 'free'}
그 라이브러리는 말씀하신 것처럼 부동소수점 연산도 사용할 수 있지만 화폐 기호를 표시하거나 자릿수 구분 등 포매팅을 할 때도 유용하게 사용할 수 있습니다.

2024-06-19 04:09 UTC, joonhok-fittube approved these changes
LGTM!

2024-06-19 05:14 UTC, merged