[#41] 사진 업로드 수정, 캐러셀 구현
f-lab-edu/Share-The-Journey pull request #42
Opened 2024-08-06 11:20 UTC by ohgus

관련 이슈: #41 

## 사진 업로드 수정
- 여러 장의 사진 업로드 가능하게 수정
- places 컬렉션 imgUrls 필드에 imgUrl을 배열로 저장하게 수정

## 카드 컴포넌트 이미지
- imgUrls의 첫 번째 사진을 렌더링

## 캐러셀 구현
- swiper 라이브러리 적용
- 이미지가 한 장 이상이면 캐러셀이 적용됨

### 단일 이미지

![image](https://github.com/user-attachments/assets/df8bdd67-ed94-4f2b-b672-d2a9c5fd3bde)

### 여러장의 이미지

![image](https://github.com/user-attachments/assets/6e04a987-d40d-402f-98dd-528ea2714e80)

2024-08-06 12:24 UTC, joonhok-fittube requested changes

2024-08-06 12:24 UTC, joonhok-fittube commented on src/app/upload/page.tsx
> +      setFiles(Array.from(e.target.files));
이렇게 하면 이미 이미지를 선택했다가 파일 업로드 버튼을 다시 눌러서 이미지를 추가하려는 경우에 기존에 선택한 이미지들을 없어져버릴 거에요. 이미 선택한 이미지를 제거하는 방법이 없다면 이렇게 동작하는게 맞을 수도 있긴 한데 어떻게 하는게 좋을까요?

2024-08-06 12:24 UTC, joonhok-fittube commented on src/app/upload/page.tsx
> +          const imageRef = ref(storage, `images/${file.name}`);
파이어스토어에서 파일 이름으로 사용할 수 있는 캐릭터에 규칙이 있을 거에요. 만약 파일 이름에 특수문자가 있다든지해서 그 규칙에 어긋나게 되면 문제가 생길 겁니다. 그 부분 확인해주시고 필요하다면 적절히 변경해서 사용해주세요. base64 인코딩 등을 사용해볼 수 있을 겁니다.

2024-08-06 12:24 UTC, joonhok-fittube commented on src/app/upload/page.tsx
> +        imgUrls = ['/default.png'];
이거는 꼭 이렇게 해야 되나요? 그냥 빈 배열로 처리하면 어떤 문제가 있죠?

2024-08-06 12:34 UTC, ohgus commented on src/app/upload/page.tsx
> +        imgUrls = ['/default.png'];
빈 배열로 넘겨도 문제가 없지만 이미지를 로드하는 페이지 마다 이미지가 있는지 확인하고 없으면 디폴트 이미지를 넣어주게 했었는데 그것보다 선택된 이미지가 없으면 아예 디폴트 이미지를 추가해서 코드의 중복을 줄이는게 좋지 않을까 생각해서 이렇게 했습니다!

2024-08-06 13:01 UTC, ohgus commented on src/app/upload/page.tsx
> +      setFiles(Array.from(e.target.files));
파일을 선택하는 창에서 기존에 선택한 파일을 유지시켜주지 않아서 현재 방식도 괜찮을거 같다고 생각합니다!

2024-08-06 13:10 UTC, ohgus commented on src/app/upload/page.tsx
> +          const imageRef = ref(storage, `images/${file.name}`);
```
const encodeFileName = (fileName: string) => {
    return btoa(fileName); // base64 encode the file name
  };

const encodedFileName = encodeFileName(file.name);
const imageRef = ref(storage, `images/${encodedFileName}`);
```
이렇게 수정하면 될까요?

2024-08-07 11:23 UTC, joonhok-fittube commented on src/app/upload/page.tsx
> +      setFiles(Array.from(e.target.files));
네, 알겠습니다!

2024-08-07 11:28 UTC, joonhok-fittube commented on src/app/upload/page.tsx
> +          const imageRef = ref(storage, `images/${file.name}`);
이거 제가 말씀드린 규칙을 확인해보신건가요? 안 해보신거면 아래 링크에서 확인해보세요.

https://firebase.google.com/docs/firestore/quotas

2024-08-07 11:29 UTC, joonhok-fittube commented on src/app/upload/page.tsx
> +        imgUrls = ['/default.png'];
이거는 그렇게 하지 마시고, 원래대로 하시는게 더 좋습니다. 그리고 이미지 컴포넌트에 디폴트 이미지를 세팅하는 방법이 분명 있을 거에요. 혹시 없으면 커스텀 컴포넌트를 만들어서 사용하셔도 됩니다.

2024-08-08 10:00 UTC, ohgus commented on src/app/upload/page.tsx
> +        imgUrls = ['/default.png'];
@joonhok-fittube 기존 방식으로 변경했습니다!

2024-08-08 10:07 UTC, ohgus commented on src/app/upload/page.tsx
> +          const imageRef = ref(storage, `images/${file.name}`);
@joonhok-fittube 이 부분은 제가 어떤 규칙을 적용해야 하는지 헷갈립니다... 필드, 문서 이름 규칙을 따라야 하는건지 아니면 문서 크기 제약을 따라야 하는건지 정확히 모르겠습니다 ㅜ

2024-08-19 05:11 UTC, merged